export type TarotCard = {
  id: string;
  name: string;
  ancestralName: string;
  overview: string;
  light: string;
  shadow: string;
  message: string;
  mantra: string;
  architecture: string;
  wound: string;
  healing: string;
  ancestralMantra: string;
};

export type TarotSuit = {
  label: string;
  cards: TarotCard[];
};

export const tarotData: Record<string, TarotSuit> = {
  "major": {
    "label": "Große Arkana",
    "cards": [
      {
        "id": "major-1",
        "name": "Der Narr",
        "ancestralName": "0 Der Narr",
        "overview": "",
        "light": "Offenheit für einen Anfang, dessen Verlauf noch nicht feststeht. Der Narr bringt Beweglichkeit dorthin, wo Erfahrung bereits zu einer Grenze geworden ist.",
        "shadow": "Freiheit kann in Unverbindlichkeit kippen; ebenso kann Angst vor dem Unbekannten jeden ersten Schritt verhindern.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Der Befreiungssprung: Mut, eine völlig neue Geschichte zu schreiben, die nicht auf den Schmerzen der Vergangenheit basiert.",
        "mantra": "Spüre beide Füße. Lass den Atem weit werden und frage: Welcher kleine Schritt fühlt sich zugleich neu und sicher genug an?",
        "architecture": "Der Nullpunkt der Ahnenlinie",
        "wound": "Die lähmende Angst, die Familie durch Eigenständigkeit zu „verraten“; das Gefühl, ohne die alten Regeln schutzlos zu sein.",
        "healing": "Der Befreiungssprung: Mut, eine völlig neue Geschichte zu schreiben, die nicht auf den Schmerzen der Vergangenheit basiert.",
        "ancestralMantra": "Ich bin frei, meine eigene Geschichte zu beginnen, ohne um Erlaubnis zu fragen."
      },
      {
        "id": "major-2",
        "name": "Der Magier",
        "ancestralName": "I Magier",
        "overview": "",
        "light": "Gebündelte Gestaltungskraft: Idee, Wille, Sprache und Handlung beginnen zusammenzuarbeiten.",
        "shadow": "Kontrolle, Selbstüberschätzung oder das Gefühl völliger Ohnmacht trennen dich von deiner tatsächlichen Wirksamkeit.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Manifestation: Das Erkennen, dass du die bewusste Gestalterin deiner Realität bist und alte Muster aktiv umschreiben kannst.",
        "mantra": "Richte die Wirbelsäule auf. Welche Fähigkeit ist jetzt bereits in deinen Händen verfügbar?",
        "architecture": "Die Werkstatt der Selbstwirksamkeit",
        "wound": "Das Gefühl der Machtlosigkeit; die Überzeugung, dass man das „Schicksal“ der Familie (z.B. Depression oder Mangel) passiv ertragen muss.",
        "healing": "Manifestation: Das Erkennen, dass du die bewusste Gestalterin deiner Realität bist und alte Muster aktiv umschreiben kannst.",
        "ancestralMantra": "Ich besitze die Kraft und alle Werkzeuge, um mein Erbe in Gold zu verwandeln."
      },
      {
        "id": "major-3",
        "name": "Die Hohepriesterin",
        "ancestralName": "II Hohepriesterin",
        "overview": "",
        "light": "Stilles Wissen, feine Wahrnehmung und die Fähigkeit, zwischen Worten zu hören.",
        "shadow": "Rückzug kann zum Versteck werden; fremde Stimmen können die eigene Intuition übertönen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Ahnen-Intuition: Der Zugang zum tiefen, instinktiven Wissen deiner weiblichen Linie; das Heilen durch das Aussprechen der Wahrheit.",
        "mantra": "Lege eine Hand unter den Nabel. Welche Antwort ist im Körper schon da, bevor der Verstand sie erklärt?",
        "architecture": "Das Archiv der Ahnengeheimnisse",
        "wound": "Familiäre Tabus und das „Verschweigen“ von Frauenthemen; Intuition, die als „Verrücktsein“ abgetan wurde.",
        "healing": "Ahnen-Intuition: Der Zugang zum tiefen, instinktiven Wissen deiner weiblichen Linie; das Heilen durch das Aussprechen der Wahrheit.",
        "ancestralMantra": "Ich vertraue der Stimme meiner weisen Ahninnen, die in mir flüstert."
      },
      {
        "id": "major-4",
        "name": "Die Herrscherin",
        "ancestralName": "III Herrscherin",
        "overview": "",
        "light": "Nährende Schöpferkraft, Sinnlichkeit und Wachstum aus einem sicheren inneren Boden.",
        "shadow": "Überfürsorge, Selbstvernachlässigung oder der Zwang zu gefallen machen Fülle von Zustimmung abhängig.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Die nährende Urkraft: Heilung der mütterlichen Linie durch radikale Selbstfürsorge und das Erschaffen von emotionaler Fülle.",
        "mantra": "Spüre Bauch und Becken. Was würde dich heute nähren, ohne dass du es erst verdienen musst?",
        "architecture": "Der Thron der geheilten Mutter",
        "wound": "Die Mutternarbe: Emotionale Kälte, Konkurrenz der Mutter zur Tochter oder eine Mutter, die selbst nie genährt wurde.",
        "healing": "Die nährende Urkraft: Heilung der mütterlichen Linie durch radikale Selbstfürsorge und das Erschaffen von emotionaler Fülle.",
        "ancestralMantra": "Ich bin die liebevolle Mutter, die ich selbst als Kind so sehr gebraucht hätte."
      },
      {
        "id": "major-5",
        "name": "Der Herrscher",
        "ancestralName": "IV Herrscher",
        "overview": "",
        "light": "Klare Führung, tragfähige Grenzen und Verantwortung für den eigenen Raum.",
        "shadow": "Starre Kontrolle oder Angst vor Autorität lassen Schutz zu Enge werden.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Gesunde Struktur: Die Fähigkeit, dir selbst einen sicheren Rahmen zu geben und „Nein“ zu sagen, ohne hart oder kalt zu werden.",
        "mantra": "Spüre deinen Rücken. Welche Grenze gibt dir Halt, ohne dein Herz zu schließen?",
        "architecture": "Das Schutzgerüst des Hauses",
        "wound": "Patriarchale Härte; ein Vater- oder Ahnenbild, das nur durch Kontrolle und Unterdrückung von Gefühlen Autorität erlangte.",
        "healing": "Gesunde Struktur: Die Fähigkeit, dir selbst einen sicheren Rahmen zu geben und „Nein“ zu sagen, ohne hart oder kalt zu werden.",
        "ancestralMantra": "Ich erschaffe mir einen Raum voll Sicherheit, in dem meine Seele aufrechter stehen kann."
      },
      {
        "id": "major-6",
        "name": "Der Hierophant",
        "ancestralName": "V Hierophant",
        "overview": "",
        "light": "Weitergegebenes Wissen, Zugehörigkeit und die bewusste Prüfung von Werten und Regeln.",
        "shadow": "Dogmen, blinder Gehorsam oder Rebellion um jeden Preis verhindern eine selbst gewählte Haltung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Eigene Ethik: Die Entwicklung eines eigenen Wertesystems, das auf deiner Wahrheit basiert, nicht auf dem Regelwerk der Ahnen.",
        "mantra": "Atme in Kehle und Brustbein. Welche übernommene Regel darfst du heute in eine eigene Wahrheit übersetzen?",
        "architecture": "Die Befreiung von Dogmen",
        "wound": "Das Brave-Tochter-Syndrom: „Das gehört sich nicht“, „Was denken die Leute?“; blinder Gehorsam gegenüber Traditionen.",
        "healing": "Eigene Ethik: Die Entwicklung eines eigenen Wertesystems, das auf deiner Wahrheit basiert, nicht auf dem Regelwerk der Ahnen.",
        "ancestralMantra": "Ich folge meinem eigenen inneren Ruf, nicht den veralteten Geboten meiner Herkunft."
      },
      {
        "id": "major-7",
        "name": "Die Liebenden",
        "ancestralName": "VI Liebenden",
        "overview": "",
        "light": "Resonanz, Beziehung und eine Wahl, die mit den eigenen Werten übereinstimmt.",
        "shadow": "Anpassung, Verschmelzung oder Entscheidungsvermeidung opfern Selbstkontakt für Bindung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Bewusste Entscheidung: Die Heilung von Co-Abhängigkeiten; sich selbst so sehr zu lieben, dass man nur noch gesunde Verbindungen wählt.",
        "mantra": "Spüre Herz und Solarplexus gleichzeitig. Welche Wahl wahrt Nähe und lässt dich dennoch bei dir?",
        "architecture": "Das Zimmer der Selbstwahl",
        "wound": "Bindungsmuster, die auf Abhängigkeit oder dem Wunsch nach „Rettung“ basieren, um der Einsamkeit der Familie zu entfliehen.",
        "healing": "Bewusste Entscheidung: Die Heilung von Co-Abhängigkeiten; sich selbst so sehr zu lieben, dass man nur noch gesunde Verbindungen wählt.",
        "ancestralMantra": "Ich wähle die Liebe, die mein wahres Wesen spiegelt und meine Freiheit ehrt."
      },
      {
        "id": "major-8",
        "name": "Der Wagen",
        "ancestralName": "VII Wagen",
        "overview": "",
        "light": "Gerichtete Kraft, Selbstführung und Bewegung trotz widersprüchlicher Impulse.",
        "shadow": "Übersteuerung, rastloses Vorwärtsdrängen oder innere Zerrissenheit verbrauchen Energie ohne Richtung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Selbstbestimmung: Die Zügel des eigenen Lebens fest in die Hand nehmen und mit klarer Absicht in die eigene Zukunft steuern.",
        "mantra": "Drücke die Füße sanft in den Boden. Wohin will deine Kraft, wenn du nichts beweisen musst?",
        "architecture": "Der Auszug aus dem Ahnenhaus",
        "wound": "Fremdsteuerung; das Gefühl, nur die Ambitionen der Eltern zu erfüllen, oder die ständige Flucht vor den eigenen Wurzeln.",
        "healing": "Selbstbestimmung: Die Zügel des eigenen Lebens fest in die Hand nehmen und mit klarer Absicht in die eigene Zukunft steuern.",
        "ancestralMantra": "Ich bin die Lenkerin meines Schicksals und fahre mutig in meine eigene Freiheit."
      },
      {
        "id": "major-9",
        "name": "Die Kraft",
        "ancestralName": "VIII Kraft",
        "overview": "",
        "light": "Sanfte Stärke: Instinkt und Bewusstsein begegnen sich, ohne einander zu bezwingen.",
        "shadow": "Unterdrückte Wut, Härte gegen dich selbst oder Angst vor der eigenen Intensität binden Lebenskraft.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Innere Stärke: Die sanfte Versöhnung mit dem „inneren Tier“; Schmerz und Wut in schöpferische Leidenschaft verwandeln.",
        "mantra": "Löse Kiefer und Hände. Wie verändert sich deine Kraft, wenn sie nicht kämpfen muss?",
        "architecture": "Der Garten der Integration",
        "wound": "Unterdrückte Wut über die Rollenbilder; Scham über die eigene wilde, ungebändigte Seite (Lilith-Thematik).",
        "healing": "Innere Stärke: Die sanfte Versöhnung mit dem „inneren Tier“; Schmerz und Wut in schöpferische Leidenschaft verwandeln.",
        "ancestralMantra": "Ich schließe Frieden mit dem Feuer in meinem Blut und nutze es für mein Wachstum."
      },
      {
        "id": "major-10",
        "name": "Der Eremit",
        "ancestralName": "IX Eremit",
        "overview": "",
        "light": "Innere Sammlung, reife Selbstbefragung und Klarheit jenseits äußerer Ablenkung.",
        "shadow": "Isolation oder endloses Nachdenken können echte Begegnung und Bewegung ersetzen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Inneres Licht: Die bewusste Einkehr, um die Perlen der Weisheit aus der eigenen Geschichte zu bergen und sich selbst zu finden.",
        "mantra": "Schließe für drei Atemzüge die Augen. Welche leise Erkenntnis möchte mit zurück in dein Leben?",
        "architecture": "Die Kammer der Selbsterkenntnis",
        "wound": "Isolation im Schmerz; das Gefühl, die einzige in der Familie zu sein, die „sieht“, was falsch läuft (die Narbe des schwarzen Schafes).",
        "healing": "Inneres Licht: Die bewusste Einkehr, um die Perlen der Weisheit aus der eigenen Geschichte zu bergen und sich selbst zu finden.",
        "ancestralMantra": "In der Stille meiner Einsamkeit finde ich das Licht, das meinen Weg erleuchtet."
      },
      {
        "id": "major-11",
        "name": "Das Rad des Schicksals",
        "ancestralName": "X Schicksalsrad",
        "overview": "",
        "light": "Zyklen, Wendepunkte und das Erkennen wiederkehrender Bewegungen.",
        "shadow": "Kontrollzwang oder Fatalismus machen aus Veränderung entweder Kampf oder Ausgeliefertsein.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Der Durchbruch: Das Erkennen des Moments, in dem man das Rad anhalten und die Richtung der Generationen ändern kann.",
        "mantra": "Spüre die Bewegung deines Atems. Was kehrt wieder - und welche neue Antwort ist diesmal möglich?",
        "architecture": "Der Hebel zur Transformation",
        "wound": "Das Gefühl, in einem ewigen Kreislauf aus Pech, Armut oder Beziehungsleid festzustecken (Karmische Last).",
        "healing": "Der Durchbruch: Das Erkennen des Moments, in dem man das Rad anhalten und die Richtung der Generationen ändern kann.",
        "ancestralMantra": "Ich stoppe das Rad der Wiederholung hier und jetzt; ich bin der Wendepunkt."
      },
      {
        "id": "major-12",
        "name": "Die Gerechtigkeit",
        "ancestralName": "XI Gerechtigkeit",
        "overview": "",
        "light": "Wahrhaftigkeit, Konsequenz und ein Ausgleich, der Verantwortung einschließt.",
        "shadow": "Selbstverurteilung, Schuldverschiebung oder starres Rechthaben verhindern echte Klärung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Radikale Wahrheit: Die klare Trennung: Was gehört den Ahnen (ihr Schmerz, ihre Taten) und was gehört wirklich zu mir?",
        "mantra": "Finde deine körperliche Mitte. Was ist dein Anteil - und was darf bei den anderen bleiben?",
        "architecture": "Die Waage des Karma-Ausgleichs",
        "wound": "Ungerechtigkeit in der Familie; Schuldgefühle, die von Generation zu Generation weitergereicht wurden (Übernahme von Fremdschuld).",
        "healing": "Radikale Wahrheit: Die klare Trennung: Was gehört den Ahnen (ihr Schmerz, ihre Taten) und was gehört wirklich zu mir?",
        "ancestralMantra": "Ich gebe zurück, was nicht mein ist, und bleibe in meiner eigenen Wahrheit."
      },
      {
        "id": "major-13",
        "name": "Der Gehängte",
        "ancestralName": "XII Gehängter",
        "overview": "",
        "light": "Eine bewusste Pause verändert die Perspektive und löst festgehaltene Lösungen.",
        "shadow": "Erstarrung, Selbstaufgabe oder passives Warten können wie Hingabe aussehen, ohne es zu sein.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Perspektivwechsel: Das freiwillige Loslassen der Opferidentität; das System durch Glück statt durch Leid ehren.",
        "mantra": "Gib für einen Moment das Tun auf. Was wird sichtbar, wenn dein Körper nichts lösen muss?",
        "architecture": "Die Umkehrung der Loyalität",
        "wound": "Die Opferrolle; das Gefühl, leiden zu müssen, weil die Frauen der Familie vor dir auch gelitten haben (Solidaritäts-Leid).",
        "healing": "Perspektivwechsel: Das freiwillige Loslassen der Opferidentität; das System durch Glück statt durch Leid ehren.",
        "ancestralMantra": "Ich lasse das Leid los und ehre meine Ahnen durch mein persönliches Glück."
      },
      {
        "id": "major-14",
        "name": "Der Tod",
        "ancestralName": "XIII Tod",
        "overview": "",
        "light": "Ein Ende schafft Raum für eine Form, die vorher nicht entstehen konnte.",
        "shadow": "Festhalten, vorweggenommene Katastrophe oder die Vermeidung von Trauer verlängern abgeschlossene Zyklen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Transformation: Das notwendige Ende einer Identität, die nicht deine ist, um Platz für dein wahres Ich zu machen.",
        "mantra": "Atme länger aus als ein. Was darf heute ein klares Ende bekommen, damit Energie zurückkehrt?",
        "architecture": "Das Sterben der alten Maske",
        "wound": "Die panische Angst vor dem Kontaktabbruch oder dem „Tod“ der Rolle als die brave, funktionierende Tochter.",
        "healing": "Transformation: Das notwendige Ende einer Identität, die nicht deine ist, um Platz für dein wahres Ich zu machen.",
        "ancestralMantra": "Ich lasse die alte Maske sterben, damit mein wahres Wesen endlich atmen kann."
      },
      {
        "id": "major-15",
        "name": "Die Mäßigkeit",
        "ancestralName": "XIV Mäßigkeit",
        "overview": "",
        "light": "Regulation, Mischung und das Finden eines heilsamen Maßes zwischen Gegensätzen.",
        "shadow": "Übermaß, innere Zersplitterung oder vorschnelle Harmonie umgehen die notwendige Abstimmung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Alchemie: Die Harmonisierung aller Anteile; das Mischen der Ahnen-Energie zu einer neuen, heilenden Essenz.",
        "mantra": "Beobachte deinen Atemrhythmus. Welche Dosis von Nähe, Aktivität oder Ruhe ist heute wirklich stimmig?",
        "architecture": "Die Heilung der Ahnen-Flüsse",
        "wound": "Innere Zerrissenheit zwischen den Fronten (z.B. zwischen Mutter und Vater); emotionale Extreme.",
        "healing": "Alchemie: Die Harmonisierung aller Anteile; das Mischen der Ahnen-Energie zu einer neuen, heilenden Essenz.",
        "ancestralMantra": "Ich bringe Frieden und Gleichgewicht in die Flüsse meiner Herkunft."
      },
      {
        "id": "major-16",
        "name": "Der Teufel",
        "ancestralName": "XV Teufel",
        "overview": "",
        "light": "Gebundene Lebenskraft wird sichtbar: Begehren, Abhängigkeit, Scham und Macht können ehrlich betrachtet werden.",
        "shadow": "Verdrängung oder zwanghafte Wiederholung halten Bindungen aufrecht, die längst Wahlfreiheit kosten.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Wahre Entfesselung: Das Erkennen, dass die Ketten der Manipulation nur lose umgelegt sind, sobald man die Wahrheit sieht.",
        "mantra": "Spüre, wo dein Körper eng wird. Welche Bindung verliert Macht, sobald du sie ohne Scham benennst?",
        "architecture": "Die Entlarvung der Fesseln",
        "wound": "Toxische Verstrickungen; emotionale Erpressung; Süchte, die als „Familientradition“ getarnt sind.",
        "healing": "Wahre Entfesselung: Das Erkennen, dass die Ketten der Manipulation nur lose umgelegt sind, sobald man die Wahrheit sieht.",
        "ancestralMantra": "Keine alte Verstrickung ist stark genug für mein erwachtes Bewusstsein."
      },
      {
        "id": "major-17",
        "name": "Der Turm",
        "ancestralName": "XVI Turm",
        "overview": "",
        "light": "Eine nicht mehr tragfähige Struktur bricht auf und setzt gebundene Wahrheit frei.",
        "shadow": "Krisenvermeidung oder dauernde Alarmbereitschaft lassen Veränderung bedrohlicher werden als nötig.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Befreiungsschlag: Das Ende der falschen Sicherheit; Platz schaffen für ein ehrliches, stabiles Fundament.",
        "mantra": "Orientiere dich im Raum und finde drei sichere Punkte. Was bleibt wahr, auch wenn eine alte Form fällt?",
        "architecture": "Der Einsturz des Lügengebäudes",
        "wound": "Plötzliche Krisen oder das schmerzhafte Zerbrechen der Illusion einer „heilen Welt“, wenn Geheimnisse gelüftet werden.",
        "healing": "Befreiungsschlag: Das Ende der falschen Sicherheit; Platz schaffen für ein ehrliches, stabiles Fundament.",
        "ancestralMantra": "Was zerbricht, war nicht wahr; ich baue mein Leben auf festem Grund neu auf."
      },
      {
        "id": "major-18",
        "name": "Der Stern",
        "ancestralName": "XVII Stern",
        "overview": "",
        "light": "Erneuerung, Vertrauen und eine feine Ausrichtung auf das, was wieder möglich wird.",
        "shadow": "Entmutigung oder spirituelles Übergehen von Schmerz trennen Hoffnung von echter Erfahrung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Inspiration: Die Heilung deiner selbst wirkt als Leuchtturm für künftige Generationen; du wirst zur Segnung deiner Linie.",
        "mantra": "Öffne den Brustraum, ohne dich zu überstrecken. Welcher winzige Hoffnungsschimmer ist heute körperlich glaubwürdig?",
        "architecture": "Die Quelle für die Nachkommen",
        "wound": "Die Überzeugung, die eigene Linie sei „verflucht“ oder vom Pech verfolgt; tiefe Hoffnungslosigkeit.",
        "healing": "Inspiration: Die Heilung deiner selbst wirkt als Leuchtturm für künftige Generationen; du wirst zur Segnung deiner Linie.",
        "ancestralMantra": "Ich bin das heilende Licht und die Hoffnung für alle, die nach mir kommen."
      },
      {
        "id": "major-19",
        "name": "Der Mond",
        "ancestralName": "XVIII Mond",
        "overview": "",
        "light": "Unbewusste Bilder, Ahnungen und Gefühle bewegen sich unterhalb eindeutiger Gewissheit.",
        "shadow": "Angst, Projektion oder die Verwechslung von Intuition und Alarm verzerren Wahrnehmung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Schattenintegration: Das Durchwandern der Angst, um die spirituelle Tiefe und die verborgenen Gaben der Ahnen zu finden.",
        "mantra": "Spüre den Boden und benenne das Jetzt. Welche Empfindung ist real - und welche Geschichte legt dein Kopf darüber?",
        "architecture": "Die Reise durch das Unbewusste",
        "wound": "Tiefe, irrationale Ängste und Alpträume, die aus kollektiven Traumata der Ahnen stammen (Krieg, Flucht).",
        "healing": "Schattenintegration: Das Durchwandern der Angst, um die spirituelle Tiefe und die verborgenen Gaben der Ahnen zu finden.",
        "ancestralMantra": "Ich wandle das Dunkle meiner Ahnen in reine, intuitive Weisheit um."
      },
      {
        "id": "major-20",
        "name": "Die Sonne",
        "ancestralName": "XIX Sonne",
        "overview": "",
        "light": "Lebendigkeit, Sichtbarkeit und die Erlaubnis, Freude ohne Rechtfertigung zu empfangen.",
        "shadow": "Leistungsdruck, erzwungene Positivität oder Angst vor Sichtbarkeit dämpfen den eigenen Ausdruck.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Volle Klarheit: Das Leben in der eigenen Wahrheit; Lebensfreude, die nicht mehr von der Zustimmung der Eltern abhängt.",
        "mantra": "Wende dein Gesicht dem Licht zu. Wo darf Freude heute einfach Energie sein, ohne Aufgabe?",
        "architecture": "Das Strahlen der Authentizität",
        "wound": "Die Narbe der Maskerade; nur geliebt werden, wenn man strahlt und keine „Probleme“ macht.",
        "healing": "Volle Klarheit: Das Leben in der eigenen Wahrheit; Lebensfreude, die nicht mehr von der Zustimmung der Eltern abhängt.",
        "ancestralMantra": "Ich strahle in meiner eigenen Wahrheit, vollkommen frei von Scham."
      },
      {
        "id": "major-21",
        "name": "Das Gericht",
        "ancestralName": "XX Gericht",
        "overview": "",
        "light": "Ein innerer Ruf bringt Vergangenes in einen größeren Zusammenhang und ermöglicht eine neue Antwort.",
        "shadow": "Selbstanklage oder das Warten auf äußere Absolution halten alte Urteile im Körper lebendig.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Auferstehung: Die Vergebung für sich selbst und die Ahnen; die Erkenntnis, dass du niemandem mehr etwas schuldest.",
        "mantra": "Atme in den Rückenraum. Welcher alte Ruf darf beantwortet werden, ohne dass du die Vergangenheit wiederholen musst?",
        "architecture": "Die Erlösung der Ahnenlinie",
        "wound": "Das Gefühl, ständig unter dem strengen Urteil der (verstorbenen) Ahnen zu stehen; ewige Rechtfertigung.",
        "healing": "Auferstehung: Die Vergebung für sich selbst und die Ahnen; die Erkenntnis, dass du niemandem mehr etwas schuldest.",
        "ancestralMantra": "Ich vergebe der Vergangenheit und erlöse mich selbst in die Freiheit."
      },
      {
        "id": "major-22",
        "name": "Die Welt",
        "ancestralName": "XXI Welt",
        "overview": "",
        "light": "Integration, Ganzheit und das bewusste Schließen eines vollständigen Erfahrungsbogens.",
        "shadow": "Perfektionismus oder fehlender Abschluss verhindern, dass Erreichtes im Körper ankommen darf.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Ankunft im Selbst: Die Vollendung der Heilreise; du bist in dir selbst zu Hause und mit dem Kosmos verbunden.",
        "mantra": "Spüre deinen ganzen Körper als einen Raum. Was darfst du würdigen, bevor der nächste Zyklus beginnt?",
        "architecture": "Das vollendete Ahnen-Haus",
        "wound": "Das Gefühl, nirgendwo wirklich „hinzugehören“; eine tiefe, innere Heimatlosigkeit.",
        "healing": "Ankunft im Selbst: Die Vollendung der Heilreise; du bist in dir selbst zu Hause und mit dem Kosmos verbunden.",
        "ancestralMantra": "Ich bin ganz, ich bin heil, ich bin endlich bei mir selbst angekommen."
      }
    ]
  },
  "wands": {
    "label": "Stäbe",
    "cards": [
      {
        "name": "Ass der Stäbe",
        "ancestralName": "As der Stäbe",
        "overview": "",
        "light": "Ein ursprünglicher Schöpfungsimpuls will Form annehmen.",
        "shadow": "Zu viel Druck oder zu wenig Erlaubnis lässt den Funken verlöschen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Ur-Energie: Die Erlaubnis, das eigene Feuer hell brennen zu lassen, ohne sich für andere klein zu machen.",
        "mantra": "Spüre Wärme in Bauch und Händen. Welcher Impuls braucht heute nur einen ersten Ausdruck?",
        "architecture": "Der Funke zur Heilung",
        "wound": "Unterdrückte Leidenschaft; die Angst, durch Erfolg oder Schönheit den Neid der Mutter oder Schwester zu wecken.",
        "healing": "Ur-Energie: Die Erlaubnis, das eigene Feuer hell brennen zu lassen, ohne sich für andere klein zu machen.",
        "ancestralMantra": "Mein inneres Feuer brennt frei, hell und unaufhaltsam für mich selbst.",
        "id": "wands-1"
      },
      {
        "name": "Zwei der Stäbe",
        "ancestralName": "Zwei der Stäbe",
        "overview": "",
        "light": "Vision und Standortbestimmung öffnen den Blick über das Bekannte hinaus.",
        "shadow": "Planung wird zur Schutzschleife, wenn kein wirklicher Schritt folgt.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Weltenblick: Den eigenen Horizont jenseits der familiären Grenzen planen und die eigene Macht anerkennen.",
        "mantra": "Richte den Blick in die Ferne und dann auf deine Füße: Welcher Weg verbindet beides?",
        "architecture": "Planung des neuen Weges",
        "wound": "Unentschlossenheit; das ständige Warten auf die Erlaubnis der Familie, bevor man einen eigenen Schritt wagt.",
        "healing": "Weltenblick: Den eigenen Horizont jenseits der familiären Grenzen planen und die eigene Macht anerkennen.",
        "ancestralMantra": "Ich plane mein Leben nach meinen eigenen Visionen und meiner eigenen Kraft.",
        "id": "wands-2"
      },
      {
        "name": "Drei der Stäbe",
        "ancestralName": "Drei der Stäbe",
        "overview": "",
        "light": "Die eigene Energie beginnt, in die Welt hinauszuwirken und Resonanz zu empfangen.",
        "shadow": "Ungeduld oder Angst vor Größe lassen Expansion wie Gefahr erscheinen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Expansion: Das tiefe Vertrauen, dass der eigene, neue Weg sicher ist und die kommenden Generationen inspiriert.",
        "mantra": "Weite den Brustkorb. Wie viel mehr Raum darf deine Vision heute einnehmen?",
        "architecture": "Weitblick über Generationen",
        "wound": "Stillstand; die Angst vor dem Erfolg, weil man niemanden in der Herkunftsfamilie „überholen“ möchte.",
        "healing": "Expansion: Das tiefe Vertrauen, dass der eigene, neue Weg sicher ist und die kommenden Generationen inspiriert.",
        "ancestralMantra": "Ich vertraue dem Weg, den ich für mich gewählt habe; ich darf wachsen.",
        "id": "wands-3"
      },
      {
        "name": "Vier der Stäbe",
        "ancestralName": "Vier der Stäbe",
        "overview": "",
        "light": "Gemeinsam getragene Freude schafft Sicherheit und einen Ort zum Ankommen.",
        "shadow": "Harmonie kann zur Fassade werden, wenn Spannungen keinen Platz haben.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Heimat in sich: Die Schaffung einer inneren Stabilität, die wahre Zugehörigkeit ohne Maske ermöglicht.",
        "mantra": "Spüre den Boden unter dir. Mit wem darf sich Erfolg sicher und ehrlich anfühlen?",
        "architecture": "Ein sicheres inneres Zuhause",
        "wound": "Engstirnigkeit; das Verharren im familiären „Kokon“, auch wenn dieser einengend und unfrei ist.",
        "healing": "Heimat in sich: Die Schaffung einer inneren Stabilität, die wahre Zugehörigkeit ohne Maske ermöglicht.",
        "ancestralMantra": "Ich bin sicher in mir selbst, egal wo ich bin und wer mich umgibt.",
        "id": "wands-4"
      },
      {
        "name": "Fünf der Stäbe",
        "ancestralName": "Fünf der Stäbe",
        "overview": "",
        "light": "Reibung macht Unterschiede, Kräfte und ungeklärte Rangordnungen sichtbar.",
        "shadow": "Vergleich und Konkurrenz können Energie binden, die eigentlich Entwicklung sucht.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Wachstums-Impuls: Die Wandlung von Neid in Inspiration; die Erkenntnis, dass der Erfolg anderer Frauen dich stärkt.",
        "mantra": "Lockere Schultern und Kiefer. Welche Spannung will bewegt statt gewonnen werden?",
        "architecture": "Dynamische Reibung",
        "wound": "Vernichtende Rivalität unter Schwestern; das Gefühl, dass nur eine Frau im Raum „die Beste“ sein darf.",
        "healing": "Wachstums-Impuls: Die Wandlung von Neid in Inspiration; die Erkenntnis, dass der Erfolg anderer Frauen dich stärkt.",
        "ancestralMantra": "Dein Leuchten dimmt mein Licht nicht; es erinnert mich an mein eigenes Feuer.",
        "id": "wands-5"
      },
      {
        "name": "Sechs der Stäbe",
        "ancestralName": "Sechs der Stäbe",
        "overview": "",
        "light": "Anerkennung lässt gelebte Kompetenz sichtbar werden und stärkt den nächsten Schritt.",
        "shadow": "Applausabhängigkeit oder Angst vor Neid trennen Erfolg vom eigenen inneren Maßstab.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Selbstwert: Den eigenen Erfolg feiern, weil er sich für dich richtig anfühlt, nicht um andere zu beeindrucken.",
        "mantra": "Nimm eine aufrechte Haltung ein. Kannst du deinen Erfolg für drei Atemzüge selbst anerkennen?",
        "architecture": "Anerkennung der Wahrheit",
        "wound": "Die Sucht nach Anerkennung durch Leistung; das Gefühl, nur durch Siege im Außen etwas wert zu sein.",
        "healing": "Selbstwert: Den eigenen Erfolg feiern, weil er sich für dich richtig anfühlt, nicht um andere zu beeindrucken.",
        "ancestralMantra": "Ich feiere meine Erfolge für mich selbst und ruhe in meinem eigenen Wert.",
        "id": "wands-6"
      },
      {
        "name": "Sieben der Stäbe",
        "ancestralName": "Sieben der Stäbe",
        "overview": "",
        "light": "Das eigene Feuer braucht eine Grenze, damit es nicht von fremden Erwartungen überrannt wird.",
        "shadow": "Dauerabwehr hält den Körper im Kampf, auch wenn keine aktuelle Gefahr besteht.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Standhaftigkeit: Ein felsenfestes Stehen zu den eigenen Werten, ohne in die Defensive gehen zu müssen.",
        "mantra": "Spüre deine Standfläche. Welches klare Nein schützt heute ein lebendiges Ja?",
        "architecture": "Energetische Abgrenzung",
        "wound": "Die totale Erschöpfung durch das ständige Rechtfertigen des eigenen Lebensstils vor kritischen Familienmitgliedern.",
        "healing": "Standhaftigkeit: Ein felsenfestes Stehen zu den eigenen Werten, ohne in die Defensive gehen zu müssen.",
        "ancestralMantra": "Mein Nein zu fremden Erwartungen ist ein heiliges Ja zu mir selbst.",
        "id": "wands-7"
      },
      {
        "name": "Acht der Stäbe",
        "ancestralName": "Acht der Stäbe",
        "overview": "",
        "light": "Energie beschleunigt sich; Entscheidungen, Nachrichten und Bewegungen finden zusammen.",
        "shadow": "Hast und Reizüberflutung überspringen die Regulation.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Heilungsfluss: Plötzliche Erkenntnisse zulassen; der Energie erlauben, schnell und leicht in Richtung Heilung zu fließen.",
        "mantra": "Verlangsame einen Atemzug. Welche Bewegung bleibt auch ohne Eile stimmig?",
        "architecture": "Schnelle Heilungsimpulse",
        "wound": "Eine Getriebenheit durch unbewusste Ahnen-Aufträge; das Gefühl, ständig rennen zu müssen, ohne anzukommen.",
        "healing": "Heilungsfluss: Plötzliche Erkenntnisse zulassen; der Energie erlauben, schnell und leicht in Richtung Heilung zu fließen.",
        "ancestralMantra": "Ich erlaube der Heilung, schnell, leicht und mühelos in mein Leben zu treten.",
        "id": "wands-8"
      },
      {
        "name": "Neun der Stäbe",
        "ancestralName": "Neun der Stäbe",
        "overview": "",
        "light": "Erfahrung hat Widerstandskraft aufgebaut, doch der Körper erinnert sich an frühere Kämpfe.",
        "shadow": "Wachsamkeit kann zur Dauerhaltung werden und jede Nähe als Angriff lesen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Eigene Stärke: Eine gesunde Resilienz, die auf der Integration der Narben beruht und keine neue Härte braucht.",
        "mantra": "Schau dich um und prüfe das Jetzt: Welche Anspannung darf fünf Prozent nachlassen?",
        "architecture": "Resilienz trotz Narben",
        "wound": "Tiefes Misstrauen gegenüber anderen; die Überzeugung: „Ich muss alles allein schaffen, sonst bin ich verloren.“",
        "healing": "Eigene Stärke: Eine gesunde Resilienz, die auf der Integration der Narben beruht und keine neue Härte braucht.",
        "ancestralMantra": "Ich stehe sicher auf dem Fundament meiner eigenen, geheilten Kraft.",
        "id": "wands-9"
      },
      {
        "name": "Zehn der Stäbe",
        "ancestralName": "Zehn der Stäbe",
        "overview": "",
        "light": "Verantwortung ist angewachsen und braucht eine neue Verteilung.",
        "shadow": "Überfunktionieren macht Last zur Identität und Hilfe zur Bedrohung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Bewusste Abgabe: Die radikale Entscheidung, den „Ahnen-Sack“ abzulegen und nur noch die eigene Last zu tragen.",
        "mantra": "Spüre Schultern und Rücken. Welche Aufgabe gehört nicht mehr in deine Hände?",
        "architecture": "Last der Ahnen ablegen",
        "wound": "Die „Parentifizierung“; das Tragen der emotionalen und praktischen Lasten der Eltern als wäre es die eigene Pflicht.",
        "healing": "Bewusste Abgabe: Die radikale Entscheidung, den „Ahnen-Sack“ abzulegen und nur noch die eigene Last zu tragen.",
        "ancestralMantra": "Ich gebe zurück, was nicht mein ist, und gehe leichten Fußes meinen Weg.",
        "id": "wands-10"
      },
      {
        "name": "Bube der Stäbe",
        "ancestralName": "Bube der Stäbe",
        "overview": "",
        "light": "Neugier, Mut und spielerisches Feuer wollen ohne Perfektionsanspruch erkundet werden.",
        "shadow": "Sprunghaftigkeit oder Angst vor Bewertung stoppen das Lernen zu früh.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Entdeckergeist: Mutig mit der eigenen Lebensenergie experimentieren und die Lust am Neuen ohne Erlaubnis feiern.",
        "mantra": "Bewege Hände und Arme frei. Was möchtest du ausprobieren, ohne darin schon gut sein zu müssen?",
        "architecture": "Entdeckung der Leidenschaft",
        "wound": "Die Entdeckung der eigenen Urkraft; das Kind, das seine Talente aus Bescheidenheit oder Angst verstecken musste.",
        "healing": "Entdeckergeist: Mutig mit der eigenen Lebensenergie experimentieren und die Lust am Neuen ohne Erlaubnis feiern.",
        "ancestralMantra": "Ich erlaube mir, meine wilde und leidenschaftliche Seite neu zu entdecken.",
        "id": "wands-11"
      },
      {
        "name": "Ritter der Stäbe",
        "ancestralName": "Ritter der Stäbe",
        "overview": "",
        "light": "Bewegung, Wagnis und leidenschaftlicher Selbstausdruck bringen Energie in Fahrt.",
        "shadow": "Impulsivität oder Flucht nach vorn verwechselt Intensität mit Richtung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Begeisterung: Die Lebenslust zurückgewinnen und die eigene Energie fokussiert für die eigene Befreiung nutzen.",
        "mantra": "Spüre Herzschlag und Füße zugleich. Welche mutige Handlung bleibt geerdet?",
        "architecture": "Mutiger Selbstausdruck",
        "wound": "Ein impulsives Ausbrechen aus der Familie ohne echten Plan; blinder Aktivismus als Fluchtreaktion.",
        "healing": "Begeisterung: Die Lebenslust zurückgewinnen und die eigene Energie fokussiert für die eigene Befreiung nutzen.",
        "ancestralMantra": "Ich folge meinem inneren Feuer mit Klarheit, Fokus und großem Mut.",
        "id": "wands-12"
      },
      {
        "name": "Königin der Stäbe",
        "ancestralName": "Königin der Stäbe",
        "overview": "",
        "light": "Verkörperte Ausstrahlung: Die eigene Wärme nährt, ohne sich kleiner zu machen.",
        "shadow": "Selbstzweifel oder Konkurrenz lassen Sichtbarkeit vom Blick anderer abhängen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Die Strahlende: Eine charismatische Person, die andere Menschen durch das eigene Licht erhebt (Integration der Schwester-/Brudernarbe).",
        "mantra": "Richte dich auf. Wie fühlt sich Präsenz an, wenn niemand überstrahlt werden muss?",
        "architecture": "Andere Frauen strahlen lassen",
        "wound": "Die Frau, die andere Frauen klein macht oder als Konkurrenz sieht, um die eigene Unsicherheit zu kaschieren.",
        "healing": "Die Strahlende: Eine charismatische Person, die andere Menschen durch das eigene Licht erhebt (Integration der Schwester-/Brudernarbe).",
        "ancestralMantra": "Ich hebe andere Frauen empor, indem ich selbst in meiner vollen Kraft strahle.",
        "id": "wands-13"
      },
      {
        "name": "König der Stäbe",
        "ancestralName": "König der Stäbe",
        "overview": "",
        "light": "Reife Schöpferkraft setzt Vision in klare Führung und langfristige Wirkung um.",
        "shadow": "Dominanz oder Überforderung entsteht, wenn alles durch den eigenen Willen gehen soll.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Schöpferkraft: Die weise Führung der eigenen Lebenskraft, um visionäre Projekte und ein neues Leben zu erschaffen.",
        "mantra": "Atme in den Rücken. Welche Vision braucht Führung - und welche braucht Vertrauen?",
        "architecture": "Energie in Schöpfung lenken",
        "wound": "Cholerik oder Machtmissbrauch in der Ahnenlinie; Energie, die zerstörerisch statt schöpferisch eingesetzt wurde.",
        "healing": "Schöpferkraft: Die weise Führung der eigenen Lebenskraft, um visionäre Projekte und ein neues Leben zu erschaffen.",
        "ancestralMantra": "Ich nutze meine Kraft weise, um Neues und Schönes in die Welt zu bringen.",
        "id": "wands-14"
      }
    ]
  },
  "cups": {
    "label": "Kelche",
    "cards": [
      {
        "name": "Ass der Kelche",
        "ancestralName": "As der Kelche",
        "overview": "",
        "light": "Emotionale Offenheit und neue Verbundenheit werden spürbar.",
        "shadow": "Sehnsucht kann nach außen greifen, wenn die eigene innere Quelle unzugänglich wirkt.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Selbstnährung: Die Entdeckung, dass du dir die emotionale Zuwendung selbst geben kannst, die dir fehlte.",
        "mantra": "Lege eine Hand aufs Herz. Welche Empfindung darf da sein, ohne sofort beantwortet zu werden?",
        "architecture": "Ursprung der Heilung",
        "wound": "Emotionale Leere; das Gefühl, dass Liebe eine knappe Ressource ist, die man sich verdienen muss.",
        "healing": "Selbstnährung: Die Entdeckung, dass du dir die emotionale Zuwendung selbst geben kannst, die dir fehlte.",
        "ancestralMantra": "Ich bin meine eigene Quelle und nähre mich mit bedingungsloser Liebe.",
        "id": "cups-1"
      },
      {
        "name": "Zwei der Kelche",
        "ancestralName": "Zwei der Kelche",
        "overview": "",
        "light": "Gegenseitigkeit entsteht dort, wo zwei Menschen sich zeigen, ohne sich zu verlieren.",
        "shadow": "Verschmelzung oder Projektion macht Beziehung zum Ersatz für Selbstkontakt.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Innere Hochzeit: Die Versöhnung zwischen deinem Erwachsenen-Ich und dem Kind, das nie richtig gesehen wurde.",
        "mantra": "Spüre dein Herz und deine Körpergrenzen. Was ist Verbindung - und was ist Übernahme?",
        "architecture": "Innere Kind-Heilung",
        "wound": "Co-Abhängigkeit; die Tendenz, in Beziehungen die bedürftige Mutter oder das rettende Kind zu spielen.",
        "healing": "Innere Hochzeit: Die Versöhnung zwischen deinem Erwachsenen-Ich und dem Kind, das nie richtig gesehen wurde.",
        "ancestralMantra": "Ich reiche meinem inneren Kind die Hand und schließe Frieden mit mir selbst.",
        "id": "cups-2"
      },
      {
        "name": "Drei der Kelche",
        "ancestralName": "Drei der Kelche",
        "overview": "",
        "light": "Geteilte Freude, weibliche Resonanz und Gemeinschaft stärken emotionale Beweglichkeit.",
        "shadow": "Gruppendruck, Ausgrenzung oder verdeckte Rivalität trüben Zugehörigkeit.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Heiliger Kreis: Die Erkenntnis, dass Heilung im Kreise von Frauen geschieht, die sich gegenseitig stützen statt zu bewerten.",
        "mantra": "Spüre, wie dein Körper auf Unterstützung reagiert. Bei wem musst du dich nicht kleiner machen?",
        "architecture": "Frauenlinie-Support",
        "wound": "Rivalität unter Frauen; das Erbe einer Mutter, die andere Frauen (oder die eigene Tochter) als Bedrohung sah.",
        "healing": "Heiliger Kreis: Die Erkenntnis, dass Heilung im Kreise von Frauen geschieht, die sich gegenseitig stützen statt zu bewerten.",
        "ancestralMantra": "Ich erkenne das Licht in meinen Schwestern und heile gemeinsam mit ihnen.",
        "id": "cups-3"
      },
      {
        "name": "Vier der Kelche",
        "ancestralName": "Vier der Kelche",
        "overview": "",
        "light": "Rückzug schützt vor Überforderung und zeigt zugleich, was emotional nicht mehr erreicht.",
        "shadow": "Abschottung kann Möglichkeiten unsichtbar machen, bevor sie wirklich geprüft wurden.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Achtsame Präsenz: Die Fähigkeit, Gefühle sicher zuzulassen, ohne von ihnen überflutet zu werden oder sich zu verschließen.",
        "mantra": "Nimm deine Müdigkeit ernst. Brauchst du Schutz, Bewegung oder eine neue Einladung?",
        "architecture": "Der emotionale Schutzraum",
        "wound": "Emotionale Taubheit; ein Schutzmechanismus, um den Schmerz über die Abwesenheit der Mutter nicht fühlen zu müssen.",
        "healing": "Achtsame Präsenz: Die Fähigkeit, Gefühle sicher zuzulassen, ohne von ihnen überflutet zu werden oder sich zu verschließen.",
        "ancestralMantra": "Ich achte meine Grenzen und erlaube mir, in meinem sicheren Raum zu fühlen.",
        "id": "cups-4"
      },
      {
        "name": "Fünf der Kelche",
        "ancestralName": "Fünf der Kelche",
        "overview": "",
        "light": "Trauer würdigt einen Verlust und macht den noch vorhandenen Halt wieder sichtbar.",
        "shadow": "Fixierung auf das Verlorene bindet den Blick an eine einzige Zeitrichtung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Akzeptanz: Die schmerzhafte, aber befreiende Einsicht, dass die Vergangenheit nicht mehr geändert werden kann.",
        "mantra": "Lass den Ausatem weich werden. Was darf betrauert werden - und was trägt dich weiterhin?",
        "architecture": "Aktive Trauerarbeit",
        "wound": "Das starre Festhalten an der Enttäuschung; ein Leben im Schatten dessen, was die Mutter nicht geben konnte.",
        "healing": "Akzeptanz: Die schmerzhafte, aber befreiende Einsicht, dass die Vergangenheit nicht mehr geändert werden kann.",
        "ancestralMantra": "Ich lasse die Tränen fließen und werde frei für die Liebe, die heute auf mich wartet.",
        "id": "cups-5"
      },
      {
        "name": "Sechs der Kelche",
        "ancestralName": "Sechs der Kelche",
        "overview": "",
        "light": "Erinnerung, Herkunft und innere Kindanteile treten in Beziehung zum Heute.",
        "shadow": "Nostalgie oder alte Rollen können Gegenwart und Vergangenheit vermischen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Essenz-Bergung: Die Fähigkeit, das Gute aus der Kindheit zu bewahren, ohne die Narben zu verleugnen.",
        "mantra": "Spüre dein heutiges Alter im Körper. Was braucht das frühere Ich jetzt von dir?",
        "architecture": "Wurzel-Integration",
        "wound": "Nostalgie, die verklärt oder schmerzt; das Gefühl, dass die „gute alte Zeit“ eine Lüge oder verloren ist.",
        "healing": "Essenz-Bergung: Die Fähigkeit, das Gute aus der Kindheit zu bewahren, ohne die Narben zu verleugnen.",
        "ancestralMantra": "Ich berge die verborgenen Schätze meiner Herkunft und lasse den Ballast zurück.",
        "id": "cups-6"
      },
      {
        "name": "Sieben der Kelche",
        "ancestralName": "Sieben der Kelche",
        "overview": "",
        "light": "Viele emotionale Möglichkeiten verlangen Unterscheidung statt schnelle Wahl.",
        "shadow": "Fantasie, Idealisierung oder Überflutung verdecken das tatsächlich Stimmige.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Klare Vision: Das Durchschauen von Illusionen; die Entscheidung für eine Realität, die auf Wahrheit basiert.",
        "mantra": "Schließe kurz die Augen. Welche Möglichkeit macht deinen Atem ruhig und weit?",
        "architecture": "Visionäre Klärung",
        "wound": "Flucht in Tagträume oder Idealisierung der Mutter, um die harte Realität der Ablehnung nicht sehen zu müssen.",
        "healing": "Klare Vision: Das Durchschauen von Illusionen; die Entscheidung für eine Realität, die auf Wahrheit basiert.",
        "ancestralMantra": "Ich wähle bewusst die Wege, die meiner Seele und meiner Wahrheit dienen.",
        "id": "cups-7"
      },
      {
        "name": "Acht der Kelche",
        "ancestralName": "Acht der Kelche",
        "overview": "",
        "light": "Ein emotionaler Zyklus ist ausgeschöpft; der Weg führt aus dem Vertrauten heraus.",
        "shadow": "Bleiben aus Schuld oder Gehen aus Flucht verhindern einen ehrlichen Abschied.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Selbstbefreiung: Den Mut finden, einen Ort des Mangels endgültig zu verlassen, um das eigene Glück zu suchen.",
        "mantra": "Spüre den Rücken beim Weggehen. Was darfst du würdigen, bevor du dich löst?",
        "architecture": "Emotionaler Aufbruch",
        "wound": "Das Verbleiben in emotionaler Armut aus falscher Loyalität oder Angst vor der Einsamkeit außerhalb der Familie.",
        "healing": "Selbstbefreiung: Den Mut finden, einen Ort des Mangels endgültig zu verlassen, um das eigene Glück zu suchen.",
        "ancestralMantra": "Ich lasse den Ort des emotionalen Mangels hinter mir und gehe mutig ins Licht.",
        "id": "cups-8"
      },
      {
        "name": "Neun der Kelche",
        "ancestralName": "Neun der Kelche",
        "overview": "",
        "light": "Genuss und innere Zufriedenheit dürfen empfangen und im Körper verankert werden.",
        "shadow": "Kompensation oder die Jagd nach Erfüllung von außen lässt das Genug nie ankommen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Selbstgenügsamkeit: Die tiefe innere Zufriedenheit, die entsteht, wenn man sich selbst emotional sicher hält.",
        "mantra": "Nimm einen angenehmen Reiz bewusst wahr. Kannst du ihn empfangen, ohne mehr daraus machen zu müssen?",
        "architecture": "Emotionale Autarkie",
        "wound": "Ersatzbefriedigung (Essen, Kaufen, Bestätigung), um das emotionale Loch der Kindheit zu stopfen.",
        "healing": "Selbstgenügsamkeit: Die tiefe innere Zufriedenheit, die entsteht, wenn man sich selbst emotional sicher hält.",
        "ancestralMantra": "Mein Herz ist aus sich selbst heraus erfüllt; ich bin mir vollkommen genug.",
        "id": "cups-9"
      },
      {
        "name": "Zehn der Kelche",
        "ancestralName": "Zehn der Kelche",
        "overview": "",
        "light": "Emotionale Verbundenheit wird zum tragenden Feld für Beziehungen und Generationen.",
        "shadow": "Das Bild der perfekten Familie kann ungelöste Spannungen unsichtbar machen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Authentischer Friede: Ein echtes Gefühl der Zugehörigkeit, das auf Wahrheit und geheilten Beziehungen basiert.",
        "mantra": "Spüre, wo Zugehörigkeit weich wird. Welche Form von Familie entspricht deiner Wahrheit?",
        "architecture": "Die geheilte Linie",
        "wound": "Die Aufrechterhaltung der „perfekten Fassade“, während es im Inneren der Familie bröckelt.",
        "healing": "Authentischer Friede: Ein echtes Gefühl der Zugehörigkeit, das auf Wahrheit und geheilten Beziehungen basiert.",
        "ancestralMantra": "Heilung fließt durch mich zurück zu meinen Ahnen und vorwärts zu meinen Kindern.",
        "id": "cups-10"
      },
      {
        "name": "Bube der Kelche",
        "ancestralName": "Bube der Kelche",
        "overview": "",
        "light": "Feine Gefühle, Imagination und das verletzliche innere Kind finden eine Sprache.",
        "shadow": "Überempfindlichkeit oder Rückzug entstehen, wenn jedes Gefühl sofort erklärt werden soll.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Gefühlsausdruck: Das Kind lernt, seine emotionale Not mitzuteilen und darf sagen, was es fühlt.",
        "mantra": "Frage dein Inneres: Wenn dieses Gefühl ein Bild wäre, welches wäre es?",
        "architecture": "Das verletzte Kind artikuliert sich",
        "wound": "Das verletzte innere Kind, das beginnt, seine Gefühle zu artikulieren; das weinende Kind, das niemand hört.",
        "healing": "Gefühlsausdruck: Das Kind lernt, seine emotionale Not mitzuteilen und darf sagen, was es fühlt.",
        "ancestralMantra": "Ich darf sagen, was ich fühle, und werde endlich gehört.",
        "id": "cups-11"
      },
      {
        "name": "Ritter der Kelche",
        "ancestralName": "Ritter der Kelche",
        "overview": "",
        "light": "Das Herz bewegt sich auf etwas zu und wagt einen aufrichtigen emotionalen Ausdruck.",
        "shadow": "Idealisierung oder Retterenergie verspricht mehr, als geerdet gehalten werden kann.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Herzenskrieger: Die Fähigkeit, aktiv für die eigene Heilung loszugehen und das Herz mutig zu öffnen.",
        "mantra": "Spüre Herz und Beine. Welche Geste ist romantisch und zugleich realistisch?",
        "architecture": "Aktive Suche nach Herzöffnung",
        "wound": "Die Suche nach emotionaler Heilung; der Drang, das Herz zu öffnen; die ewige Suche nach dem „Retter“.",
        "healing": "Herzenskrieger: Die Fähigkeit, aktiv für die eigene Heilung loszugehen und das Herz mutig zu öffnen.",
        "ancestralMantra": "Ich öffne mein Herz mutig für meine eigene Heilung.",
        "id": "cups-12"
      },
      {
        "name": "Königin der Kelche",
        "ancestralName": "Königin der Kelche",
        "overview": "",
        "light": "Tiefe Empathie wird zur Ressource, wenn sie in sicheren Grenzen ruht.",
        "shadow": "Übernahme fremder Gefühle oder Selbstaufgabe lässt Fürsorge auslaugen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Die Heilerin: Verkörperung der nährenden Kraft, die man einst suchte; gesunde Empathie leben.",
        "mantra": "Stell dir eine weiche Grenze um deinen Körper vor. Was kannst du fühlen, ohne es zu tragen?",
        "architecture": "Die geheilte Mutter-Energie",
        "wound": "Die geheilte Mutter-Energie; die Fähigkeit, sich selbst zu nähren; die opferbereite oder instabile Mutter.",
        "healing": "Die Heilerin: Verkörperung der nährenden Kraft, die man einst suchte; gesunde Empathie leben.",
        "ancestralMantra": "Ich verkörpere die nährende Kraft, die ich einst suchte.",
        "id": "cups-13"
      },
      {
        "name": "König der Kelche",
        "ancestralName": "König der Kelche",
        "overview": "",
        "light": "Emotionale Reife hält Wellen aus, ohne sie zu unterdrücken oder an andere weiterzugeben.",
        "shadow": "Kontrollierte Fassade oder verdeckte Überflutung erschwert ehrlichen Kontakt.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Der Ruhepol: Ein ruhiger Pol im Sturm der Familiengefühle sein; Souveränität über die eigene Gefühlswelt.",
        "mantra": "Atme tief in den Bauch. Welche Emotion kannst du führen, ohne sie wegzumachen?",
        "architecture": "Emotionale Meisterschaft",
        "wound": "Emotionale Meisterschaft; tiefe Gelassenheit gegenüber alten Dramen; Unterdrückung von Gefühlen.",
        "healing": "Der Ruhepol: Ein ruhiger Pol im Sturm der Familiengefühle sein; Souveränität über die eigene Gefühlswelt.",
        "ancestralMantra": "Ich ruhe in mir, unabhängig vom Sturm der Ahnen.",
        "id": "cups-14"
      }
    ]
  },
  "coins": {
    "label": "Münzen",
    "cards": [
      {
        "name": "Ass der Münzen",
        "ancestralName": "As der Münzen",
        "overview": "",
        "light": "Eine konkrete Möglichkeit bietet Boden für Wachstum, Versorgung und Verkörperung.",
        "shadow": "Mangelangst oder vorschnelles Festhalten kann den Samen ersticken.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Neues Wachstum: Die Chance auf ein stabiles Fundament; der Aufbau eines Selbstwerts, der materiell greifbar wird.",
        "mantra": "Spüre Füße und Hände. Welcher kleine reale Schritt stärkt heute dein Fundament?",
        "architecture": "Physisches Fundament",
        "wound": "Ein tief sitzendes Gefühl von Wertlosigkeit; das Erbe einer Linie, die sich immer als „klein“ empfand.",
        "healing": "Neues Wachstum: Die Chance auf ein stabiles Fundament; der Aufbau eines Selbstwerts, der materiell greifbar wird.",
        "ancestralMantra": "Ich bin würdig, Stabilität, Wohlstand und Fülle in meinem Leben zu verkörpern.",
        "id": "coins-1"
      },
      {
        "name": "Zwei der Münzen",
        "ancestralName": "Zwei der Münzen",
        "overview": "",
        "light": "Mehrere Anforderungen brauchen Rhythmus, Priorität und bewegliche Balance.",
        "shadow": "Dauerndes Jonglieren hält das Nervensystem beschäftigt und verhindert echte Wahl.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Wahre Balance: Ein spielerischer Umgang mit den Anforderungen; Altes und Neues flexibel in Einklang bringen.",
        "mantra": "Verlagere dein Gewicht von einem Fuß zum anderen. Was darf heute weniger wichtig sein?",
        "architecture": "Balance zw. Erbe und Leben",
        "wound": "Der Stress durch das Jonglieren fremder Erwartungen und der Versuch, zwei Welten gleichzeitig zu bedienen.",
        "healing": "Wahre Balance: Ein spielerischer Umgang mit den Anforderungen; Altes und Neues flexibel in Einklang bringen.",
        "ancestralMantra": "Ich jongliere meine Aufgaben mit Leichtigkeit und vertraue meinem Rhythmus.",
        "id": "coins-2"
      },
      {
        "name": "Drei der Münzen",
        "ancestralName": "Drei der Münzen",
        "overview": "",
        "light": "Können wächst in Zusammenarbeit, Resonanz und sorgfältigem Aufbau.",
        "shadow": "Leistungszweifel oder fehlende Anerkennung lassen den eigenen Beitrag unsichtbar werden.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Meisterschaft: Der bewusste Aufbau des eigenen „Hauses“; Anerkennung der eigenen Fachkompetenz im Leben.",
        "mantra": "Spüre deine Hände. Welche Fähigkeit darfst du benennen und mit anderen verbinden?",
        "architecture": "Aktive Arbeit am Ahnen-Haus",
        "wound": "Die fehlende Anerkennung für die eigene Identitätsarbeit; das Gefühl, dass die eigene Mühe niemals „zählt“.",
        "healing": "Meisterschaft: Der bewusste Aufbau des eigenen „Hauses“; Anerkennung der eigenen Fachkompetenz im Leben.",
        "ancestralMantra": "Jeder Schritt meiner inneren Arbeit festigt das Fundament meiner Freiheit.",
        "id": "coins-3"
      },
      {
        "name": "Vier der Münzen",
        "ancestralName": "Vier der Münzen",
        "overview": "",
        "light": "Bewahren schafft Sicherheit, solange Schutz nicht zur Erstarrung wird.",
        "shadow": "Festhalten an Geld, Kontrolle oder Gewissheiten verengt den Lebensfluss.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Innere Sicherheit: Die Erkenntnis, dass wahre Stabilität aus dem Inneren kommt und Grenzen Liebe schützen.",
        "mantra": "Öffne und schließe langsam die Hände. Was braucht Schutz - und was wieder Bewegung?",
        "architecture": "Schutz der Grenzen",
        "wound": "Zwanghaftes Festhalten an starren Strukturen oder Besitz aus Angst, sonst keine Identität mehr zu haben.",
        "healing": "Innere Sicherheit: Die Erkenntnis, dass wahre Stabilität aus dem Inneren kommt und Grenzen Liebe schützen.",
        "ancestralMantra": "Ich bin sicher in mir selbst; ich muss nicht mehr an alten Lasten festhalten.",
        "id": "coins-4"
      },
      {
        "name": "Fünf der Münzen",
        "ancestralName": "Fünf der Münzen",
        "overview": "",
        "light": "Erlebter Mangel und Ausschluss berühren Würde, Körper und Zugehörigkeit.",
        "shadow": "Scham isoliert und macht vorhandene Unterstützung schwer erreichbar.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Fülle-Bewusstsein: Die Heilung der „Armut im Geist“; sich für die Fülle des Lebens und der Liebe öffnen.",
        "mantra": "Spüre einen tragenden Kontaktpunkt. Welche Hilfe wäre heute konkret annehmbar?",
        "architecture": "Heilung des Mangels",
        "wound": "Das kollektive Mangeldenken der Ahnen („Wir haben nichts verdient“); das Gefühl, spirituell heimatlos zu sein.",
        "healing": "Fülle-Bewusstsein: Die Heilung der „Armut im Geist“; sich für die Fülle des Lebens und der Liebe öffnen.",
        "ancestralMantra": "Ich heile den Mangel in meinem Geist und empfange die Fülle des Universums.",
        "id": "coins-5"
      },
      {
        "name": "Sechs der Münzen",
        "ancestralName": "Sechs der Münzen",
        "overview": "",
        "light": "Geben und Empfangen suchen einen würdigen, transparenten Ausgleich.",
        "shadow": "Abhängigkeit, Schuld oder Machtgefälle verstecken sich leicht hinter Großzügigkeit.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Großzügigkeit: Den Karma-Ausgleich vollziehen; lernen, mit offenem Herzen zu empfangen und gesund zu geben.",
        "mantra": "Beobachte deine Reaktion auf Empfang. Kannst du etwas annehmen, ohne es sofort zurückzahlen zu müssen?",
        "architecture": "Ausgleich von Geben-Nehmen",
        "wound": "Ein tiefes Ungleichgewicht im Familien-Karma; das Gefühl, immer geben zu müssen, um existieren zu dürfen.",
        "healing": "Großzügigkeit: Den Karma-Ausgleich vollziehen; lernen, mit offenem Herzen zu empfangen und gesund zu geben.",
        "ancestralMantra": "Ich löse alle alten Schuldgefühle auf und bin bereit, Fülle zu empfangen.",
        "id": "coins-6"
      },
      {
        "name": "Sieben der Münzen",
        "ancestralName": "Sieben der Münzen",
        "overview": "",
        "light": "Wachstum braucht Zeit, Pflege und eine ehrliche Zwischenbilanz.",
        "shadow": "Ungeduld oder Festhalten an versunkenen Kosten bindet weitere Kraft.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Vertrauen: Die geduldige Beobachtung des Wachstums; Wissen, dass die Saat der Heilung Zeit zum Reifen braucht.",
        "mantra": "Spüre deinen natürlichen Rhythmus. Was reift - und was darf neu entschieden werden?",
        "architecture": "Geduld mit der Heilung",
        "wound": "Frustration über das Tempo der Heilung; das Gefühl, dass sich trotz harter Arbeit am Selbst nichts ändert.",
        "healing": "Vertrauen: Die geduldige Beobachtung des Wachstums; Wissen, dass die Saat der Heilung Zeit zum Reifen braucht.",
        "ancestralMantra": "Ich vertraue dem Prozess und gebe meiner Heilung die Zeit, die sie braucht.",
        "id": "coins-7"
      },
      {
        "name": "Acht der Münzen",
        "ancestralName": "Acht der Münzen",
        "overview": "",
        "light": "Wiederholung, Handwerk und Aufmerksamkeit verwandeln Fähigkeit in Verkörperung.",
        "shadow": "Perfektionismus oder monotones Funktionieren trennt Übung von Sinn.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Hingabe: Die liebevolle Detailarbeit an den eigenen Mustern; Meisterschaft in der Dekonstruktion des Alten.",
        "mantra": "Wähle eine kleine Bewegung und führe sie langsam aus. Was lernt dein Körper durch Wiederholung?",
        "architecture": "Meisterschaft der Wandlung",
        "wound": "Sklavischer Fleiß und Perfektionismus als Überlebensstrategie, um Kritik der Ahnen zuvorzukommen.",
        "healing": "Hingabe: Die liebevolle Detailarbeit an den eigenen Mustern; Meisterschaft in der Dekonstruktion des Alten.",
        "ancestralMantra": "Ich arbeite mit Hingabe und Freude an der Architektur meiner neuen Realität.",
        "id": "coins-8"
      },
      {
        "name": "Neun der Münzen",
        "ancestralName": "Neun der Münzen",
        "overview": "",
        "light": "Eigenständigkeit, Genuss und materieller Selbstwert dürfen sichtbar werden.",
        "shadow": "Unabhängigkeit kann zur Mauer werden, wenn Bedürftigkeit beschämt bleibt.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Autarkie: Die Früchte der eigenen Ahnenarbeit allein genießen; Stolz auf die unabhängig aufgebaute Existenz.",
        "mantra": "Spüre den Raum, den du geschaffen hast. Kannst du deinen Erfolg genießen und dennoch verbunden bleiben?",
        "architecture": "Stolz auf Unabhängigkeit",
        "wound": "Die materielle oder emotionale Abhängigkeit vom Status der Familie; Angst, ohne das Erbe nichts zu sein.",
        "healing": "Autarkie: Die Früchte der eigenen Ahnenarbeit allein genießen; Stolz auf die unabhängig aufgebaute Existenz.",
        "ancestralMantra": "Ich genieße die Früchte meiner eigenen Arbeit und ruhe in meiner Unabhängigkeit.",
        "id": "coins-9"
      },
      {
        "name": "Zehn der Münzen",
        "ancestralName": "Zehn der Münzen",
        "overview": "",
        "light": "Erbe, Langfristigkeit und generationenübergreifende Stabilität werden bewusst gestaltet.",
        "shadow": "Tradition, Besitz oder Familienloyalität können individuelle Wahrheit überdecken.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Wahres Erbe: Die Erschaffung eines Erbes (geistig & materiell), das nachfolgenden Generationen Flügel verleiht.",
        "mantra": "Spüre deine Wurzeln und deinen Scheitel. Was möchtest du bewahren - und was anders weitergeben?",
        "architecture": "Vollendetes Ahnen-Haus",
        "wound": "Der „goldene Käfig“ der Familientradition; Reichtum, der mit der Verpflichtung zur Unfreiheit erkauft wurde.",
        "healing": "Wahres Erbe: Die Erschaffung eines Erbes (geistig & materiell), das nachfolgenden Generationen Flügel verleiht.",
        "ancestralMantra": "Ich hinterlasse ein Erbe der Freiheit und des Friedens für alle, die nach mir kommen.",
        "id": "coins-10"
      },
      {
        "name": "Page der Münzen",
        "ancestralName": "Page der Münzen",
        "overview": "",
        "light": "Praktische Neugier lädt dazu ein, Körper, Ressourcen und neue Fähigkeiten ernst zu nehmen.",
        "shadow": "Unsicherheit oder Aufschub hält Lernen im Kopf statt in der Erfahrung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Körperliebe: Den eigenen Körper als Tempel pflegen; achtsamer Umgang mit der eigenen physischen Präsenz.",
        "mantra": "Berühre einen Gegenstand bewusst. Was möchtest du durch Tun statt durch Denken verstehen?",
        "architecture": "Umgang mit dem Körper",
        "wound": "Die Vernachlässigung des Körpers als Resultat von Ahnen-Traumata; den Körper nur als „Werkzeug“ betrachten.",
        "healing": "Körperliebe: Den eigenen Körper als Tempel pflegen; achtsamer Umgang mit der eigenen physischen Präsenz.",
        "ancestralMantra": "Mein Körper ist ein heiliger Tempel der geheilten Generationen.",
        "id": "coins-11"
      },
      {
        "name": "Ritter der Münzen",
        "ancestralName": "Ritter der Münzen",
        "overview": "",
        "light": "Beständigkeit, Verlässlichkeit und ein tragfähiger Lebensrhythmus bringen Vorhaben ans Ziel.",
        "shadow": "Starrheit oder Pflichterfüllung ohne Lebendigkeit macht Sicherheit schwer.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Zuverlässigkeit: Die stetige, praktische Arbeit an einem neuen Lebensstil, der die Heilung im Alltag verankert.",
        "mantra": "Gehe drei langsame Schritte. Welches Tempo kannst du langfristig halten?",
        "architecture": "Arbeit am Lebensstil",
        "wound": "Eine starre Routine aus Angst vor Veränderung; das Festhalten an gewohnten, aber ungesunden Abläufen.",
        "healing": "Zuverlässigkeit: Die stetige, praktische Arbeit an einem neuen Lebensstil, der die Heilung im Alltag verankert.",
        "ancestralMantra": "Schritt für Schritt baue ich mir eine Realität, die meiner Seele gut tut.",
        "id": "coins-12"
      },
      {
        "name": "Königin der Münzen",
        "ancestralName": "Königin der Münzen",
        "overview": "",
        "light": "Nährende Präsenz verbindet Körperwissen, Fürsorge und materielles Gespür.",
        "shadow": "Selbstaufopferung oder Überversorgung anderer leert die eigene Basis.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Die Erderin: Eine tiefe, echte Geborgenheit verkörpern; Schöpferin eines Zuhauses, das Körper und Seele nährt.",
        "mantra": "Spüre Bauch und Becken. Welche Form von Fürsorge beginnt heute bei dir?",
        "architecture": "Körperliche Erdung",
        "wound": "Materielle Überfürsorge der Mutter bei gleichzeitiger emotionaler Kälte; Geborgenheit, die an Bedingungen geknüpft ist.",
        "healing": "Die Erderin: Eine tiefe, echte Geborgenheit verkörpern; Schöpferin eines Zuhauses, das Körper und Seele nährt.",
        "ancestralMantra": "Ich erschaffe mir ein Nest aus echter Liebe, Sicherheit und Geborgenheit.",
        "id": "coins-13"
      },
      {
        "name": "König der Münzen",
        "ancestralName": "König der Münzen",
        "overview": "",
        "light": "Verantwortung für Ressourcen schafft Stabilität, Wirksamkeit und ein gereiftes Erbe.",
        "shadow": "Status, Kontrolle oder Besitzdenken verwechselt Wert mit äußerer Absicherung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Hüter der Werte: Manifestation einer sicheren Zukunft; das neue Erbe verantwortungsbewusst schützen und leiten.",
        "mantra": "Spüre deinen Sitz und Rücken. Welche Ressource willst du verantwortlich führen statt festhalten?",
        "architecture": "Manifestation der Zukunft",
        "wound": "Den Wert eines Menschen (oder den eigenen) nur über erbrachte Leistung und Besitz definieren.",
        "healing": "Hüter der Werte: Manifestation einer sicheren Zukunft; das neue Erbe verantwortungsbewusst schützen und leiten.",
        "ancestralMantra": "Ich manifestiere Sicherheit und Wohlstand für mich und meine neue Linie.",
        "id": "coins-14"
      }
    ]
  },
  "swords": {
    "label": "Schwerter",
    "cards": [
      {
        "name": "Ass der Schwerter",
        "ancestralName": "As der Schwerter",
        "overview": "",
        "light": "Klarheit trennt Beobachtung von Erzählung und eröffnet eine wahrhaftige Entscheidung.",
        "shadow": "Schärfe kann verletzen, wenn Wahrheit ohne Beziehung oder Timing eingesetzt wird.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Geistesklarheit: Der scharfe Schnitt, der die Lügen der Ahnen von deiner eigenen Wahrheit trennt.",
        "mantra": "Spüre den Raum hinter der Stirn. Welcher einfache Satz ist wahr, ohne hart zu sein?",
        "architecture": "Schwert der Wahrheit",
        "wound": "Verwirrung durch Gaslighting in der Familie; das Gefühl, der eigenen Wahrnehmung nicht trauen zu können.",
        "healing": "Geistesklarheit: Der scharfe Schnitt, der die Lügen der Ahnen von deiner eigenen Wahrheit trennt.",
        "ancestralMantra": "Meine Wahrheit schneidet die Fesseln der familiären Täuschung durch.",
        "id": "swords-1"
      },
      {
        "name": "Zwei der Schwerter",
        "ancestralName": "Zwei der Schwerter",
        "overview": "",
        "light": "Zwei Wahrheiten oder Loyalitäten halten inne, bis eine innere Wahl möglich wird.",
        "shadow": "Vermeidung schützt kurzfristig vor Konflikt und verlängert zugleich die Spannung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Authentische Wahl: Die Entscheidung, die Loyalität zu sich selbst über die Harmonie im Familiensystem zu stellen.",
        "mantra": "Entspanne die Augen. Welche Information darfst du fühlen, statt sie weiter abzuwägen?",
        "architecture": "Der Loyalitätskonflikt",
        "wound": "Die Lähmung zwischen dem Wunsch, es den Eltern recht zu machen, und dem Drang, man selbst zu sein.",
        "healing": "Authentische Wahl: Die Entscheidung, die Loyalität zu sich selbst über die Harmonie im Familiensystem zu stellen.",
        "ancestralMantra": "Ich wähle meine eigene Wahrheit vor blinder Loyalität zum System.",
        "id": "swords-2"
      },
      {
        "name": "Drei der Schwerter",
        "ancestralName": "Drei der Schwerter",
        "overview": "",
        "light": "Ein schmerzhafter Gedanke oder Bruch wird anerkannt, damit Herz und Verstand wieder zusammenfinden.",
        "shadow": "Grübeln hält die Narbe in Alarm oder macht Schmerz zum Beweis gegen den eigenen Wert.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Initiation: Den Schmerz als Türöffner nutzen, um die Mauern um das wahre Ich einzureißen.",
        "mantra": "Lege eine Hand auf Brust und eine an die Schläfe. Was braucht Mitgefühl statt Analyse?",
        "architecture": "Herz-Geist-Heilung",
        "wound": "Der Schmerz des Selbstverrats; das Gefühl, das eigene Herz gebrochen zu haben, um „brav“ zu sein.",
        "healing": "Initiation: Den Schmerz als Türöffner nutzen, um die Mauern um das wahre Ich einzureißen.",
        "ancestralMantra": "Durch den Riss in meinem Schmerz bricht meine wahre Freiheit hervor.",
        "id": "swords-3"
      },
      {
        "name": "Vier der Schwerter",
        "ancestralName": "Vier der Schwerter",
        "overview": "",
        "light": "Das mentale System braucht Pause, Rückzug und Neuordnung.",
        "shadow": "Erstarrung oder produktives Vermeiden tarnt sich als Erholung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Heilige Stille: Ein Rückzugsort im Geist, an dem keine Stimmen von Eltern oder Ahnen mehr urteilen dürfen.",
        "mantra": "Lass den Blick weich werden. Welche Form von Ruhe stellt wirklich wieder Kontakt her?",
        "architecture": "Mentale Regeneration",
        "wound": "Totale mentale Erschöpfung durch das ständige Scannen der Umgebung, um Konflikte zu vermeiden.",
        "healing": "Heilige Stille: Ein Rückzugsort im Geist, an dem keine Stimmen von Eltern oder Ahnen mehr urteilen dürfen.",
        "ancestralMantra": "In der Stille meiner Erholung höre ich nur noch meine eigene Stimme.",
        "id": "swords-4"
      },
      {
        "name": "Fünf der Schwerter",
        "ancestralName": "Fünf der Schwerter",
        "overview": "",
        "light": "Konflikt zeigt, welchen Preis Gewinnen, Rechthaben oder Anpassung tatsächlich haben.",
        "shadow": "Abwertung und taktische Härte schützen vor Verletzlichkeit, zerstören aber Verbindung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Integrität: Die Weigerung, an destruktiven Gesprächen teilzunehmen; Ausstieg aus dem Drama-Dreieck.",
        "mantra": "Spüre die Zunge im Mund. Welches Wort kannst du weglassen, um deiner Würde treu zu bleiben?",
        "architecture": "Kommunikations-Bruch",
        "wound": "Verbale Gewalt oder passiv-aggressive Machtspiele, die als „normale Kommunikation“ vererbt wurden.",
        "healing": "Integrität: Die Weigerung, an destruktiven Gesprächen teilzunehmen; Ausstieg aus dem Drama-Dreieck.",
        "ancestralMantra": "Ich lege die Waffen nieder; dieser Kampf gehört nicht zu meiner Geschichte.",
        "id": "swords-5"
      },
      {
        "name": "Sechs der Schwerter",
        "ancestralName": "Sechs der Schwerter",
        "overview": "",
        "light": "Ein Übergang führt aus mentaler Unruhe in eine ruhigere, noch unbekannte Ordnung.",
        "shadow": "Alte Gedankenreisen können mitgenommen werden und den neuen Ort wieder besetzen.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Bewusster Übergang: Die Reise weg von einengenden Denkmustern hin zu einem neuen, freien Bewusstsein.",
        "mantra": "Spüre die Bewegung des Atems nach vorn. Welchen Gedanken musst du nicht mitnehmen?",
        "architecture": "Die mentale Reise",
        "wound": "Flucht vor den Problemen durch rein rationales Analysieren, ohne das Gefühl wirklich zu transformieren.",
        "healing": "Bewusster Übergang: Die Reise weg von einengenden Denkmustern hin zu einem neuen, freien Bewusstsein.",
        "ancestralMantra": "Ich lasse das Ufer der Erwartungen hinter mir und steure in meine Freiheit.",
        "id": "swords-6"
      },
      {
        "name": "Sieben der Schwerter",
        "ancestralName": "Sieben der Schwerter",
        "overview": "",
        "light": "Kluges Vorgehen, Diskretion und Eigenständigkeit prüfen die Grenze zwischen Strategie und Selbstverrat.",
        "shadow": "Vermeidung, Täuschung oder heimliches Handeln entstehen oft aus erwarteter Strafe.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Souveräne Klugheit: Die Fähigkeit, sich schrittweise und sicher aus toxischen Rollen herauszuarbeiten.",
        "mantra": "Spüre deinen Rücken. Welche Wahrheit braucht Schutz - und welche braucht ein offenes Wort?",
        "architecture": "Strategische Ablösung",
        "wound": "Das Verstecken der wahren Meinung; ein Leben in Heimlichkeiten, um Bestrafung zu entgehen.",
        "healing": "Souveräne Klugheit: Die Fähigkeit, sich schrittweise und sicher aus toxischen Rollen herauszuarbeiten.",
        "ancestralMantra": "Ich befreie mich klug und behutsam aus den Rollen der Vergangenheit.",
        "id": "swords-7"
      },
      {
        "name": "Acht der Schwerter",
        "ancestralName": "Acht der Schwerter",
        "overview": "",
        "light": "Innere Sätze begrenzen Handlung, obwohl im Außen mehr Spielraum vorhanden ist.",
        "shadow": "Hilflosigkeit wird stabil, wenn jeder Ausweg vorab als unmöglich bewertet wird.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Erwachen: Die Erkenntnis, dass die Fesseln nur aus alten Worten bestehen und man jederzeit gehen kann.",
        "mantra": "Bewege zuerst nur einen Finger oder Fuß. Welche minimale Wahl beweist deinem System Beweglichkeit?",
        "architecture": "Gedanken-Gefängnis",
        "wound": "Die Überzeugung, dass man „nicht anders kann“; Gefangensein in den moralischen Urteilen der Ahnen.",
        "healing": "Erwachen: Die Erkenntnis, dass die Fesseln nur aus alten Worten bestehen und man jederzeit gehen kann.",
        "ancestralMantra": "Die Schranken existieren nur so lange, wie ich an ihre Macht über mich glaube.",
        "id": "swords-8"
      },
      {
        "name": "Neun der Schwerter",
        "ancestralName": "Neun der Schwerter",
        "overview": "",
        "light": "Nächtliche Gedanken machen Angst, Schuld und unverarbeitete Bilder körperlich laut.",
        "shadow": "Katastrophisieren oder Scham isoliert das Nervensystem in einer inneren Endlosschleife.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Angst-Wandlung: Das Verständnis, dass diese Ängste nicht deine sind, sondern das Echo der Ahnen-Traumata.",
        "mantra": "Orientiere dich im Raum und verlängere den Ausatem. Was ist jetzt tatsächlich geschehen - und was befürchtest du?",
        "architecture": "Ahnen-Angst",
        "wound": "Schlaflose Nächte durch irrationale Schuldgefühle, wenn man die Regeln der „braven Tochter“ bricht.",
        "healing": "Angst-Wandlung: Das Verständnis, dass diese Ängste nicht deine sind, sondern das Echo der Ahnen-Traumata.",
        "ancestralMantra": "Ich entlasse die Schuld und die Ängste meiner Ahnen aus meinem Nervensystem.",
        "id": "swords-9"
      },
      {
        "name": "Zehn der Schwerter",
        "ancestralName": "Zehn der Schwerter",
        "overview": "",
        "light": "Ein schmerzhafter mentaler Zyklus erreicht seinen Endpunkt; Fortsetzung ist nicht mehr nötig.",
        "shadow": "Identifikation mit Niederlage oder das Wiederbeleben alter Geschichten verhindert Abschluss.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Neubeginn: Das Ende der falschen Identität; der leere Raum, in dem du dich völlig neu definieren kannst.",
        "mantra": "Spüre den Boden unter dem ganzen Körper. Welcher Satz darf hier enden?",
        "architecture": "Der totale System-Tod",
        "wound": "Der Moment, in dem das „Brave-Tochter-Programm“ zu einem Burnout oder Zusammenbruch führt.",
        "healing": "Neubeginn: Das Ende der falschen Identität; der leere Raum, in dem du dich völlig neu definieren kannst.",
        "ancestralMantra": "Das alte Denken endet hier; ich schreibe mein Leben heute vollkommen neu.",
        "id": "swords-10"
      },
      {
        "name": "Bube der Schwerter",
        "ancestralName": "Bube der Schwerter",
        "overview": "",
        "light": "Wacher Geist, Fragen und neue Perspektiven untersuchen übernommene Gewissheiten.",
        "shadow": "Misstrauen oder vorschnelle Kritik hält den Verstand ständig auf der Suche nach Gefahr.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Der Kritiker: Mutige Fragen an das System stellen; die Wahrheit hinter den Kulissen suchen.",
        "mantra": "Lass den Blick neugierig wandern. Welche Frage öffnet, statt jemanden zu prüfen?",
        "architecture": "Erster kritischer Gedanke",
        "wound": "Der erste kritische Gedanke; das Hinterfragen von Familienregeln; sagen, was die Eltern hören wollen.",
        "healing": "Der Kritiker: Mutige Fragen an das System stellen; die Wahrheit hinter den Kulissen suchen.",
        "ancestralMantra": "Ich wage es, die alten Regeln zu hinterfragen.",
        "id": "swords-11"
      },
      {
        "name": "Ritter der Schwerter",
        "ancestralName": "Ritter der Schwerter",
        "overview": "",
        "light": "Entschlossene Gedanken werden zu Sprache und Handlung.",
        "shadow": "Übereile, Angriff oder argumentative Härte überspringt Körper und Beziehung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Identitäts-Krieger: Mutig für die eigene Identität einstehen; die Zerschlagung alter Gedankenkonstrukte.",
        "mantra": "Atme einmal vollständig aus, bevor du sprichst. Welche Wahrheit bleibt danach wichtig?",
        "architecture": "Kampf für die Wahrheit",
        "wound": "Der aktive Kampf für die eigene Wahrheit; radikale Ehrlichkeit; aggressives Verteidigen vererbter Meinungen.",
        "healing": "Identitäts-Krieger: Mutig für die eigene Identität einstehen; die Zerschlagung alter Gedankenkonstrukte.",
        "ancestralMantra": "Ich stehe felsenfest zu meiner eigenen Wahrheit.",
        "id": "swords-12"
      },
      {
        "name": "Königin der Schwerter",
        "ancestralName": "Königin der Schwerter",
        "overview": "",
        "light": "Klare Unterscheidung verbindet Intelligenz mit gelebter Grenze.",
        "shadow": "Kühle Distanz oder unbarmherzige Selbstkritik schützt vor erneuter Verletzung.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Die Unabhängige: Klarer Verstand ohne emotionale Erpressung; die eigene Stimme souverän nutzen.",
        "mantra": "Spüre Herz und Kehle. Wie klingt Klarheit, wenn Würde mit im Raum bleibt?",
        "architecture": "Unabhängigkeit von der Maske",
        "wound": "Die unabhängige Frau; sie hat die Maske der „Braven Tochter“ abgelegt; die kühle, urteilende Kritikerin.",
        "healing": "Die Unabhängige: Klarer Verstand ohne emotionale Erpressung; die eigene Stimme souverän nutzen.",
        "ancestralMantra": "Ich bin die alleinige Gesetzgeberin meines Geistes.",
        "id": "swords-13"
      },
      {
        "name": "König der Schwerter",
        "ancestralName": "König der Schwerter",
        "overview": "",
        "light": "Mentale Autorität ordnet Komplexität, entscheidet verantwortlich und bleibt überprüfbar.",
        "shadow": "Überlegenheit oder Kontrolle durch Wissen trennt Vernunft von Menschlichkeit.",
        "message": "Diese Karte lädt nicht zur Vorhersage ein, sondern zu einer bewussten Neuorientierung. Eigene Weisheit: Souveräne Deutungshoheit über das eigene Leben gewinnen; objektive Beobachtung.",
        "mantra": "Richte den Kopf über dem Herzen aus. Welche Entscheidung ist klar und zugleich beziehungsfähig?",
        "architecture": "Autorität über das eigene Denken",
        "wound": "Die Autorität über das eigene Denken; setzt klare intellektuelle Grenzen; das Gesetz der Väter.",
        "healing": "Eigene Weisheit: Souveräne Deutungshoheit über das eigene Leben gewinnen; objektive Beobachtung.",
        "ancestralMantra": "Ich besitze die Deutungshoheit über mein Leben.",
        "id": "swords-14"
      }
    ]
  }
};
